### ISSUE TITLE
Projects Page content covers navigation bar on phone

### ISSUE THREAD

**Issue by cleverActon0126** [JustFoxx/justfox-website#4]
The content/image on the projects page covers the navigation which makes it impossible to navigate to the page that has been covered.

**Comment by cleverActon0126** [comment]
Phone: iPhone 12 Pro
Reso: 2532x1170

**Comment by cleverActon0126** [comment]
![image](https://user-images.githubusercontent.com/59557379/135698252-092803b9-655c-4a55-a397-fc9fd5b2abe8.jpeg)

**Comment by JustFoxx** [comment]
It will be never repaired sorry. There will be new version of website.
